### ISSUE TITLE
Shelly adapter not discovering Shelly Dimmer 2

### ISSUE THREAD

**Issue by roman-1983** [tim-hellhake/shelly-adapter#22]
I am running several Shelly Dimmer 2 but it seems that they are not discover.
I do not have problems with
- Shelly 1pm
- Shelly 2.5
They are discovered without any problem.

Gateway Version: 1.0 (actual release)
Shelly Adapter: 1.3.1 (actual release)
Shelly Dimmer 2 Firmware: 20210226-115010/v1.9.6-dimmer2@1873d25e (actual release)

All devices are available via cloud.

I assume here is a problem, can you please help me?

```Mar  6 14:27:33 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:33.524 INFO   : shelly-adapter: 40F520241D17 deviceTemperature changed from 49.77 to 49.59#033[22m#033[39m
Mar  6 14:27:35 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:35.163 INFO   : Unloading ShellyAdapter#033[22m#033[39m
Mar  6 14:27:47 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:47.491 INFO   : Loading add-on: shelly-adapter#033[22m#033[39m
Mar  6 14:27:49 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:49.515 INFO   : shelly-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3#033[22m#033[39m
Mar  6 14:27:49 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:49.582 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType#033[22m#033[39m
Mar  6 14:27:51 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:51.510 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType#033[22m#033[39m
Mar  6 14:27:54 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:54.893 INFO   : shelly-adapter: Loading add-on shelly-adapter from /home/pi/.webthings/addons/shelly-adapter#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.586 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 40F5202E56B5#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.595 INFO   : shelly-adapter: Discovered new Shelly25 with id E09806954ADF#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.599 INFO   : shelly-adapter: Detected deviceTemperature property#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.604 INFO   : shelly-adapter: Ignoring power meters in roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.607 INFO   : shelly-adapter: Configuring roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.646 INFO   : shelly-adapter: Discovered new Shelly1PM with id 8CAAB542BF3B#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.649 INFO   : shelly-adapter: Detected deviceTemperature property#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.654 INFO   : shelly-adapter: Configuring power meters#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.657 INFO   : shelly-adapter: Found power0#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.661 INFO   : shelly-adapter: No power1 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.665 INFO   : shelly-adapter: No power2 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.668 INFO   : shelly-adapter: No power3 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.671 INFO   : shelly-adapter: No switch mode found, assuming relay#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.674 INFO   : shelly-adapter: Configuring relay mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.676 INFO   : shelly-adapter: Found relay0#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.678 INFO   : shelly-adapter: No relay1 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.680 INFO   : shelly-adapter: No relay2 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.682 INFO   : shelly-adapter: No relay3 present#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.685 INFO   : shelly-adapter: Discovered new Shelly25 with id 40F520241D17#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.687 INFO   : shelly-adapter: Detected deviceTemperature property#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.689 INFO   : shelly-adapter: Ignoring power meters in roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.691 INFO   : shelly-adapter: Configuring roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.693 INFO   : shelly-adapter: Discovered new Shelly25 with id 40F52001487B#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.696 INFO   : shelly-adapter: Detected deviceTemperature property#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.698 INFO   : shelly-adapter: Ignoring power meters in roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.700 INFO   : shelly-adapter: Configuring roller mode#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.702 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 84CCA8ACB867#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.704 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 40F5202E55C1#033[22m#033[39m
Mar  6 14:27:55 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:55.706 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 40F52000E77B#033[22m#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.008 ERROR  : shelly-adapter: dgram.js:581#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.010 ERROR  : shelly-adapter:     throw errnoException(err, 'addMembership');#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.012 ERROR  : shelly-adapter:     ^#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.015 ERROR  : shelly-adapter: #033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.017 ERROR  : shelly-adapter: Error: addMembership EADDRINUSE#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.019 ERROR  : shelly-adapter:     at Socket.addMembership (dgram.js:581:11)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.022 ERROR  : shelly-adapter:     at /home/pi/.webthings/addons/shelly-adapter/node_modules/coap/lib/server.js:234:26#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.023 ERROR  : shelly-adapter:     at Array.forEach (<anonymous>)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.026 ERROR  : shelly-adapter:     at Socket.<anonymous> (/home/pi/.webthings/addons/shelly-adapter/node_modules/coap/lib/server.js:233:44)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.028 ERROR  : shelly-adapter:     at Object.onceWrapper (events.js:286:20)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.030 ERROR  : shelly-adapter:     at Socket.emit (events.js:198:13)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.031 ERROR  : shelly-adapter:     at startListening (dgram.js:128:10)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.036 ERROR  : shelly-adapter:     at state.handle.lookup (dgram.js:249:7)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[31m2021-03-06 14:27:56.038 ERROR  : shelly-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)#033[39m
Mar  6 14:27:56 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:56.041 INFO   : Plugin: shelly-adapter died, code = 1 restarting after 0#033[22m#033[39m
Mar  6 14:27:58 gateway run-app.sh[519]: #033[37m#033[2m2021-03-06 14:27:58.073 INFO   : shelly-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3#033[22m#033[39m```

**Comment by roman-1983** [comment]
ping @tim-hellhake :-)

**Comment by tim-hellhake** [comment]
Sorry I somehow missed the first notification email.
I'll try to find out what's causing the error in the log.

**Comment by tim-hellhake** [comment]
The error occurs when the COAP library tries to subscribe to the multicast group on all your network interfaces.
The adapter already found some devices, so multicast must be active on at least one interface.
I'm not sure what exactly is causing the issue.
Maybe another process of the adapter that is not controlled by the gateway is still running.
Did you try to restart the system?

Another reason could be your network setup.
Can you tell me a bit more about it?
Where is the gateway running? Docker? PI?
Is your system connected to the same network via multiple network cards?
Do you use VLAN subinterfaces?

**Comment by roman-1983** [comment]
Hi @tim-hellhake 

My System is running on a PI4.

> pi@gateway:~ $ cat /proc/version
Linux version 5.10.11-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1399 SMP Thu Jan 28 12:06:05 GMT 2021

> Maybe another process of the adapter that is not controlled by the gateway is still running.
> Did you try to restart the system?

Yes i totally restarted the system and even had re-installed it completly.

> Another reason could be your network setup.
> Can you tell me a bit more about it?
> Where is the gateway running? Docker? PI?
> Is your system connected to the same network via multiple network cards?
> Do you use VLAN subinterfaces?

I have a FritzBox 6660 running on 2,4 and 5GHz wifi with a Fritz Mesh Repeater.
My system is running on a PI 4 and is connected via Wifi AND cable - is this a problem? I didnt find a way to disable the Wifi on the PI.
I do not use VLAN sub-interfaces.


Greets
Roman

**Comment by tim-hellhake** [comment]
> My system is running on a PI 4 and is connected via Wifi AND cable - is this a problem?

It shouldn't be.
I just connected my pi to the wifi and restarted the adapter without having any errors.

**Comment by tim-hellhake** [comment]
The new updates add the option to select a specific network interface for the multicast traffic.
Can you please check if using the wifi or the eth interface works for you?

**Comment by roman-1983** [comment]
It looks like this now:
![image](https://user-images.githubusercontent.com/3573021/112531854-609f3200-8da8-11eb-88c1-7e3e25093ec5.png)


What should i enter there? my local ip address of the device?

**Comment by tim-hellhake** [comment]
You have to enter the name of the network interface.
The ethernet interface is usually called `eth0` and the wifi interface `wlan0`.

**Comment by roman-1983** [comment]
Good morning.
In the meantime i disabled wifi and tried it with `eth0`.

The shelly adapter seem to find some new shellies:

> 2021-03-26 07:42:07.905 INFO   : Loading add-on: shelly-adapter
2021-03-26 07:42:09.864 INFO   : shelly-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2021-03-26 07:42:09.930 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-03-26 07:42:11.823 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-03-26 07:42:15.046 INFO   : shelly-adapter: Loading add-on shelly-adapter from /home/pi/.webthings/addons/shelly-adapter
2021-03-26 07:42:15.613 INFO   : shelly-adapter: Starting on 192.168.178.49
2021-03-26 07:42:15.696 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id F4CFA2ECB85B
2021-03-26 07:42:15.702 INFO   : shelly-adapter: Discovered new Shelly1PM with id 8CAAB5433145
2021-03-26 07:42:15.705 INFO   : shelly-adapter: Detected deviceTemperature property
2021-03-26 07:42:15.707 INFO   : shelly-adapter: Configuring power meters
2021-03-26 07:42:15.709 INFO   : shelly-adapter: Found power0
2021-03-26 07:42:15.711 INFO   : shelly-adapter: No power1 present
2021-03-26 07:42:15.714 INFO   : shelly-adapter: No power2 present
2021-03-26 07:42:15.716 INFO   : shelly-adapter: No power3 present
2021-03-26 07:42:15.718 INFO   : shelly-adapter: No switch mode found, assuming relay
2021-03-26 07:42:15.719 INFO   : shelly-adapter: Configuring relay mode
2021-03-26 07:42:15.720 INFO   : shelly-adapter: Found relay0
2021-03-26 07:42:15.721 INFO   : shelly-adapter: No relay1 present
2021-03-26 07:42:15.722 INFO   : shelly-adapter: No relay2 present
2021-03-26 07:42:15.723 INFO   : shelly-adapter: No relay3 present
2021-03-26 07:42:15.724 INFO   : shelly-adapter: Discovered new Shelly25 with id 40F520241D17
2021-03-26 07:42:15.725 INFO   : shelly-adapter: Detected deviceTemperature property
2021-03-26 07:42:15.726 INFO   : shelly-adapter: Ignoring power meters in roller mode
2021-03-26 07:42:15.731 INFO   : shelly-adapter: Configuring roller mode
2021-03-26 07:42:16.327 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 84CCA8AE3863
2021-03-26 07:42:17.432 INFO   : shelly-adapter: 40F520241D17 rollerPosition changed from 0 to 90
2021-03-26 07:42:17.435 INFO   : shelly-adapter: 40F520241D17 rollerStopReason changed from  to normal
2021-03-26 07:42:17.437 INFO   : shelly-adapter: 40F520241D17 deviceTemperature changed from 47.86 to 47.95
2021-03-26 07:42:17.438 ERROR  : shelly-adapter: No property for rollerStopReason found
2021-03-26 07:42:17.971 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 84CCA8AE4EA6
2021-03-26 07:42:18.851 INFO   : shelly-adapter: Discovered new Shelly25 with id E09806954ADF
2021-03-26 07:42:18.853 INFO   : shelly-adapter: Detected deviceTemperature property
2021-03-26 07:42:18.854 INFO   : shelly-adapter: Ignoring power meters in roller mode
2021-03-26 07:42:18.856 INFO   : shelly-adapter: Configuring roller mode
2021-03-26 07:42:26.241 INFO   : shelly-adapter: Discovered new Shelly25 with id 40F52001487B
2021-03-26 07:42:26.243 INFO   : shelly-adapter: Detected deviceTemperature property
2021-03-26 07:42:26.244 INFO   : shelly-adapter: Ignoring power meters in roller mode
2021-03-26 07:42:26.245 INFO   : shelly-adapter: Configuring roller mode
2021-03-26 07:42:26.589 INFO   : shelly-adapter: Discovered new Shelly1PM with id 8CAAB542BF3B
2021-03-26 07:42:26.591 INFO   : shelly-adapter: Detected deviceTemperature property
2021-03-26 07:42:26.592 INFO   : shelly-adapter: Configuring power meters
2021-03-26 07:42:26.593 INFO   : shelly-adapter: Found power0
2021-03-26 07:42:26.594 INFO   : shelly-adapter: No power1 present
2021-03-26 07:42:26.595 INFO   : shelly-adapter: No power2 present
2021-03-26 07:42:26.596 INFO   : shelly-adapter: No power3 present
2021-03-26 07:42:26.598 INFO   : shelly-adapter: No switch mode found, assuming relay
2021-03-26 07:42:26.599 INFO   : shelly-adapter: Configuring relay mode
2021-03-26 07:42:26.600 INFO   : shelly-adapter: Found relay0
2021-03-26 07:42:26.601 INFO   : shelly-adapter: No relay1 present
2021-03-26 07:42:26.601 INFO   : shelly-adapter: No relay2 present
2021-03-26 07:42:26.602 INFO   : shelly-adapter: No relay3 present
2021-03-26 07:42:27.197 INFO   : shelly-adapter: Discovered new ShellyDimmer2 with id 84CCA8ACB867
2021-03-26 07:42:28.033 INFO   : shelly-adapter: 8CAAB5433145 deviceTemperature changed from 48.67 to 48.15
2021-03-26 07:42:33.844 INFO   : shelly-adapter: E09806954ADF rollerPosition changed from 0 to 100
2021-03-26 07:42:33.848 INFO   : shelly-adapter: E09806954ADF rollerStopReason changed from  to normal
2021-03-26 07:42:33.849 ERROR  : shelly-adapter: No property for rollerStopReason found
2021-03-26 07:42:36.695 INFO   : About to call startPairing on DateTimeAdapter
2021-03-26 07:42:36.697 INFO   : About to call startPairing on SpeedTestAdapter
2021-03-26 07:42:36.698 INFO   : About to call startPairing on TPLinkAdapter
2021-03-26 07:42:36.717 INFO   : About to call startPairing on SchedulerAdapter
2021-03-26 07:42:36.719 INFO   : About to call startPairing on SysteminfoAdapter
2021-03-26 07:42:36.721 INFO   : About to call startPairing on SimpleMQTTAdapter
2021-03-26 07:42:36.723 INFO   : About to call startPairing on HomeKitAdapter
2021-03-26 07:42:36.725 INFO   : About to call startPairing on ZigbeeAdapter
2021-03-26 07:42:36.727 INFO   : About to call startPairing on ThingURLAdapter
2021-03-26 07:42:36.729 INFO   : About to call startPairing on ShellyAdapter
2021-03-26 07:42:36.747 INFO   : date-time-adapter: date_adapter.py:37 INFO Log level 30
2021-03-26 07:42:36.747 INFO   : zigbee-adapter: Pairing mode started, timeout = 60
2021-03-26 07:42:36.759 INFO   : Opened a new things socket
2021-03-26 07:42:39.272 INFO   : shelly-adapter: 8CAAB542BF3B deviceTemperature changed from 40.31 to 40.16
2021-03-26 07:42:41.244 INFO   : shelly-adapter: 40F52001487B rollerPosition changed from 0 to 100
2021-03-26 07:42:41.245 INFO   : shelly-adapter: 40F52001487B rollerStopReason changed from  to normal
2021-03-26 07:42:41.246 INFO   : shelly-adapter: 40F52001487B deviceTemperature changed from 54.48 to 54.58
2021-03-26 07:42:41.251 ERROR  : shelly-adapter: No property for rollerStopReason found
2021-03-26 07:42:43.034 INFO   : shelly-adapter: 8CAAB5433145 deviceTemperature changed from 48.15 to 48.57
2021-03-26 07:42:49.046 INFO   : shelly-adapter: E09806954ADF deviceTemperature changed from 49.86 to 49.77
2021-03-26 07:42:54.282 INFO   : shelly-adapter: 8CAAB542BF3B deviceTemperature changed from 40.16 to 40.24
2021-03-26 07:42:58.248 INFO   : shelly-adapter: 40F520241D17 deviceTemperature changed from 47.95 to 47.78
2021-03-26 07:43:08.902 INFO   : shelly-adapter: 40F52001487B deviceTemperature changed from 54.58 to 54.69
2021-03-26 07:43:09.280 INFO   : shelly-adapter: 8CAAB5433145 deviceTemperature changed from 48.57 to 48.36
2021-03-26 07:43:09.288 INFO   : shelly-adapter: 8CAAB542BF3B deviceTemperature changed from 40.24 to 40.46

**But** they do not apped in the "Add Things +" overview. :-(

**Comment by tim-hellhake** [comment]
> But they do not apped in the "Add Things +" overview

Don't worry, we'll fix it :)

> IS there anything i can do?

Help me to test new updates :)

**Comment by roman-1983** [comment]
Good morning.
Now it works like a charm, thank you!
![image](https://user-images.githubusercontent.com/3573021/112711318-c209f280-8ec7-11eb-903a-28628c7c50ee.png)

**Comment by tim-hellhake** [comment]
Awesome!
