### ISSUE TITLE
Add support for shelly uni

### ISSUE THREAD

**Issue by lerrypage** [tim-hellhake/shelly-adapter#27]
the Shelly-adapter finds my shelly uni but it doesn't communicate with it. Only the two switching outputs are displayed, although it also has temperature sensors and switches. the outputs do not respond to the commands

**Comment by tim-hellhake** [comment]
Hi @lerrypage
I added properties for the inputs and the temperature sensors.
Unfortunately, I don't have a device here to test it, so you have to try it out for me.
Also, can you please enable `debug logs` in the adapter settings and attach the logs after an adapter restart?
You can find them in `https://<gateway>/settings/developer` when you click on `View Internal Logs`.

**Comment by lerrypage** [comment]
2021-06-30 06:32:23.389 INFO   : shelly-adapter: Loading add-on shelly-adapter from /home/pi/.webthings/addons/shelly-adapter
2021-06-30 06:32:23.924 ERROR  : shelly-adapter: Failed to start add-on shelly-adapter: Network interface 192.168.12.99 does not exist in lo,eth0
2021-06-30 06:32:23.926 ERROR  : shelly-adapter: Error: Network interface 192.168.12.99 does not exist in lo,eth0
2021-06-30 06:32:23.928 ERROR  : shelly-adapter:     at new ShellyAdapter (/home/pi/.webthings/addons/shelly-adapter/lib/shelly-adapter.js:71:23)
2021-06-30 06:32:23.931 ERROR  : shelly-adapter:     at /home/pi/.webthings/addons/shelly-adapter/lib/index.js:30:9
2021-06-30 06:32:23.932 ERROR  : shelly-adapter:     at Generator.next (<anonymous>)
2021-06-30 06:32:23.934 ERROR  : shelly-adapter:     at fulfilled (/home/pi/.webthings/addons/shelly-adapter/lib/index.js:10:58)
2021-06-30 06:32:23.937 INFO   : shelly-adapter: Unhandled Rejection

**Comment by lerrypage** [comment]
I'm not sure whether I have to set multicast (mcast) or unicast in Shelly. (192.168.12.125:5683)
In Firmware Update 1.10 add unicast ability for CoIoT – to decrease network traffic and better network compatibility
My Shelly works on batteries and therefore it should also have low power consumption.

**Comment by tim-hellhake** [comment]
> Error: Network interface 192.168.12.99 does not exist in lo,eth0

You entered an IP address (`192.168.12.99`) instead of a network interface (`eth0`).
Btw. the setting is optional.
You only have to fill it if the adapter uses the wrong interface.

**Comment by tim-hellhake** [comment]
> I'm not sure whether I have to set multicast (mcast) or unicast in Shelly

I think it should be multicast as the shellies library uses it to discover the devices.

**Comment by lerrypage** [comment]
2021-07-02 07:21:33.353 INFO   : shelly-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2021-07-02 07:21:33.439 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-07-02 07:21:35.086 INFO   : shelly-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-07-02 07:21:37.880 INFO   : shelly-adapter: Loading add-on shelly-adapter from /home/pi/.webthings/addons/shelly-adapter
2021-07-02 07:21:38.461 ERROR  : shelly-adapter: Failed to start add-on shelly-adapter: Network interface 192.168.12.99 does not exist in lo,eth0
2021-07-02 07:21:38.470 INFO   : shelly-adapter: Unhandled Rejection
2021-07-02 07:21:38.472 ERROR  : shelly-adapter: Error: Network interface 196.254.12.99 does not exist in lo,eth0
2021-07-02 07:21:38.473 ERROR  : shelly-adapter:     at new ShellyAdapter (/home/pi/.webthings/addons/shelly-adapter/lib/shelly-adapter.js:71:23)
2021-07-02 07:21:38.474 ERROR  : shelly-adapter:     at /home/pi/.webthings/addons/shelly-adapter/lib/index.js:30:9
2021-07-02 07:21:38.475 ERROR  : shelly-adapter:     at Generator.next (<anonymous>)
2021-07-02 07:21:38.476 ERROR  : shelly-adapter:     at fulfilled (/home/pi/.webthings/addons/shelly-adapter/lib/index.js:10:58)

I have now switched to multicast and have tried it with and without IP but without success 

I could also install Tasmota on the Shelly uni, but unfortunately the Tasmota lacks important functions, such as timer and support for 18B20 sensors. The Tasmota WebTings plugin works perfectly with my devices.

**Comment by lerrypage** [comment]
If an ESP8266 is available, you can flash a "Shelli uni" on it to test it. 
Firmware:
http://archive.shelly-support.eu/v1.10.4/SHUNI-1_build.zip
Flash-Tool Mos:
https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md
![Shelli-Pins](https://user-images.githubusercontent.com/74759294/124284617-706ba680-db4d-11eb-858b-2b64587f5556.jpg)

**Comment by lerrypage** [comment]
It's almost embarrassing, but I had to restart the Mozilla Things Gateway and suddenly my Shelly uni are displayed correctly, but I cannot activate Relay 0 or Relay 1. Only the current status is displayed here with a long delay.
